apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: gcr.io/ticketing-dev-367816/expiration
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: REDIS_HOST
              value: expiration-redis-srv
#We won't make a ClusterIP service because this service is not going to be contacted by any other part of our application directly
#anyways. We're also not going to have any network requests going directly to the expiration service
# We would only have the expiration pod container that is going to communicate
# with everything asynchronously through the nats streaming service
