apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-mongo
  template:
    metadata:
      labels:
        app: tickets-mongo
    spec:
      containers:
        - name: tickets-mongo
          image: mongo #gcr.io/ticketing-dev-367816/mongo
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-srv
spec:
  type: ClusterIP #the default(can be omitted)
  selector:
    app: tickets-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017 #by default mongodb listens to incoming requests on that port
      targetPort: 27017
